### PR TITLE
Port 2 orion

### PR DESCRIPTION
**Pull request by flampouris**
1. The mkfm is updated to compile to Orion
2. .gitignore has been added

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Something is going on here. We need to make sure that the mkmf we're pointing to with the orion file has the options for passing in the debug flag and has -link_mpi=dbg on the FFLAGS_DEBUG line

**Comment by JessicaMeixner-NOAA** [comment]
Is this an issue of not pointing to the right mkmf or did the right file in mkmf not make it to mkmf?  I know things were weird with GitHub and the mkmf PR yesterday.

**Comment by DeniseWorthen** [comment]
If I check out the emc mkmf, I see the commit from yesterday. This is commit 3f4ec81 to mkmf where Stelios corrected the template. But it is saying there are conflicts that need to be resolved to make the merge. The PR on the interface doesn't seem to be pointing to the right commit of mkmf, because the debug is still wrong.

**Comment by JessicaMeixner-NOAA** [comment]
@flampouris can you update the mkmf that this PR is pointing to?

**Review by DeniseWorthen — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Review by jiandewang — APPROVED** [review]

**Pull request merged**
